export const data = [
  {
    id: 1,
    title: "Desenvolvedor Back-end Júnior",
    description: "Estamos buscando um desenvolvedor back-end júnior para se juntar à nossa equipe e trabalhar em projetos desafiadores. O candidato ideal deve ter conhecimentos em desenvolvimento back-end com linguagens como Python ou Node.js, banco de dados SQL, Git e estar em busca de aprender e evoluir sua carreira.",
    career_focus: "Back-end",
    required_skills: [
      "Python",
      "Node.js",
      "SQL",
      "Git"
    ],
    type: "CLT",
    seniority_level: "Júnior",
    work_arrangement: "Híbrido",
    salary_range: "R$ 2.000,00 - R$ 3.000,00",
    publication: "2023-03-30",
  },  
  {
    id: 2,
    title: "Desenvolvedor Front-end Júnior",
    description: "Procuramos um desenvolvedor Front-end para trabalhar em projetos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, curioso e capaz de trabalhar em equipe.",
    career_focus: "Front-end",
    required_skills: [
      "JavaScript",
      "React",
      "Sass",
      "Git"
    ],
    type: "CLT",
    seniority_level: "Júnior",
    work_arrangement: "Remoto",
    salary_range: "R$ 3,000.00 - R$ 4,500.00",
    publication: "2023-03-31",
  },
  {
    id: 3,
    title: "Desenvolvedor Back-end Pleno",
    description: "Estamos buscando um desenvolvedor Back-end Pleno para trabalhar em nosso time e ajudar a construir soluções inovadoras para nossos clientes. O candidato ideal tem experiência em desenvolvimento de APIs, banco de dados e arquiteturas escaláveis, além de ser proativo e ter boa comunicação.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "Express",
      "MongoDB",
      "Redis",
      "PostgreSQL",
      "RESTful API",
      "Arquitetura de Microserviços"
    ],
    type: "PJ",
    seniority_level: "Pleno",
    work_arrangement: "Remoto",
    salary_range: "R$ 8.000,00 - R$ 10.000,00",
    publication: "2023-03-31",
  },  
  {
    id: 4,
    title: "Desenvolvedor Full-stack Sênior",
    description: "Estamos buscando um desenvolvedor Full-stack Sênior para liderar nosso time de desenvolvimento e construir soluções de alta qualidade para nossos clientes. O candidato ideal tem experiência em liderança de equipe, desenvolvimento front-end e back-end, bem como em gerenciamento de projetos.",
    career_focus: "Full-stack",
    required_skills: [
      "Node.js",
      "Express",
      "React",
      "Angular",
      "Vue.js",
      "MongoDB",
      "MySQL",
      "PostgreSQL",
      "AWS",
      "Docker",
      "Git",
      "TypeScript",
    ],
    type: "CLT",
    seniority_level: "Sênior",
    work_arrangement: "Presencial",
    salary_range: "R$ 15.000,00 - R$ 20.000,00",
    publication: "2023-03-29",
  },  
  {
    id: 5,
    title: "Desenvolvedor Mobile Sênior",
    description: "Estamos buscando um desenvolvedor mobile sênior para se juntar à nossa equipe de desenvolvimento. O candidato ideal tem experiência em desenvolvimento mobile nativo para iOS e Android, além de conhecimento em boas práticas de UX/UI.",
    career_focus: "Mobile",
    required_skills: [
      "React Native",
      "Swift",
      "Kotlin",
      "JavaScript",
      "Node.js",
      "Firebase",
      "Git",
    ],
    type: "CLT",
    seniority_level: "Sênior",
    work_arrangement: "Presencial",
    salary_range: "R$ 12.000,00 - R$ 15.000,00",
    publication: "2023-03-20",
  },
  {
    id: 6,
    title: "Engenheiro DevOps Pleno",
    description: "Estamos procurando um Engenheiro DevOps Pleno para integrar nossa equipe de infraestrutura e garantir o suporte e melhoria contínua de nossos serviços. O candidato ideal é apaixonado por automação, tem amplo conhecimento em ferramentas e tecnologias de infraestrutura em nuvem e é capaz de trabalhar em colaboração com equipes de desenvolvimento.",
    career_focus: "DevOps",
    required_skills: [
      "Docker",
      "Kubernetes",
      "AWS",
      "Linux",
      "Bash",
      "Python",
      "Terraform",
      "Ansible"
    ],
    type: "CLT",
    seniority_level: "Pleno",
    work_arrangement: "Remoto",
    salary_range: "R$ 8.000,00 - R$ 12.000,00",
    publication: "2023-02-28",
  }  
]