export const data = [ 
  {
    id: 1,
    title: "Desenvolvedor Front-end Júnior",
    description: "Procuramos um desenvolvedor Front-end para trabalhar em projetos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, curioso e capaz de trabalhar em equipe.",
    career_focus: "Front-end",
    required_skills: [
      "JavaScript",
      "React",
      "Sass",
      "Jest",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Júnior",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 2.500,00 - R$ 3.500,00",
    publication: "2023-04-08",
  },
  {
    id: 2,
    title: "Desenvolvedor Back-end Júnior",
    description: "Estamos em busca de um desenvolvedor back-end júnior para integrar nosso time e contribuir com o desenvolvimento de soluções inovadoras. O candidato ideal deve ter conhecimento em tecnologias como Node.js, SQL e Git, além de ser proativo, colaborativo e estar disposto a aprender.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "Express",
      "MongoDB",
      "REST API",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Júnior",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 2.500,00 - R$ 3.500,00",
    publication: "2023-04-08"
  },
  {
    id: 3,
    title: "Desenvolvedor Full-stack Júnior",
    description: "Procuramos um desenvolvedor Full-stack para trabalhar em projetos desafiadores e inovadores em um ambiente dinâmico e colaborativo. O candidato ideal é curioso, autodidata e capaz de aprender novas tecnologias rapidamente.",
    career_focus: "Full-stack",
    required_skills: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Git"
    ],
    type_contract: "PJ",
    seniority_level: "Júnior",
    type_job: "Presencial",
    location: "Cabo Frio, RJ",
    salary_range: "R$ 3.000,00 - R$ 4.500,00",
    publication: "2023-04-08"
  },
  {
    id: 4,
    title: "Desenvolvedor Front-end Pleno",
    description: "Procuramos um desenvolvedor Front-end para liderar projetos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, possui grande experiência com desenvolvimento web e é capaz de liderar uma equipe.",
    career_focus: "Front-end",
    required_skills: [
      "JavaScript",
      "React",
      "Vue.js",
      "Angular",
      "HTML",
      "CSS",
      "Sass",
      "Jest",
      "Webpack"
    ],
    type_contract: "CLT",
    seniority_level: "Pleno",
    type_job: "Presencial",
    location: "São Paulo, SP",
    salary_range: "R$ 5.000,00 - R$ 8.000,00",
    publication: "2023-04-08"
  },
  {
    id: 5,
    title: "Desenvolvedor Back-end Pleno",
    description: "Estamos em busca de um desenvolvedor Back-end Pleno para liderar projetos desafiadores em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, possui grande experiência com desenvolvimento web e é capaz de liderar uma equipe.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "PHP",
      "Python",
      "SQL",
      "MongoDB",
      "AWS",
      "Docker",
      "Git",
      "TDD"
    ],
    type_contract: "PJ",
    seniority_level: "Pleno",
    type_job: "Presencial",
    location: "Belo Horizonte, MG",
    salary_range: "R$ 6.000,00 - R$ 10.000,00",
    publication: "2023-04-08"
  },
  {
    id: 6,
    title: "Desenvolvedor Full-stack Pleno",
    description: "Estamos em busca de um desenvolvedor Full-stack Pleno para liderar projetos de alta complexidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, possui grande experiência com desenvolvimento web e é capaz de liderar uma equipe.",
    career_focus: "Full-stack",
    required_skills: [
      "JavaScript",
      "React",
      "Node.js",
      "SQL",
      "MongoDB",
      "AWS",
      "HTML",
      "CSS",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Pleno",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 7.000,00 - R$ 12.000,00",
    publication: "2023-04-08"
  },
  {
    id: 7,
    title: "Desenvolvedor Front-end Sênior",
    description: "Procuramos um desenvolvedor Front-end para liderar e trabalhar em projetos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, tem ampla experiência em liderar equipes e projetos, além de habilidades em comunicação e colaboração.",
    career_focus: "Front-end",
    required_skills: [
      "JavaScript",
      "React",
      "Redux",
      "Webpack",
      "Node.js",
      "ES6+",
      "Testing Library",
      "Styled Components",
      "Git"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "São Paulo - SP",
    salary_range: "R$ 8.000,00 - R$ 12.000,00",
    publication: "2023-04-08"
  },
  {
    id: 8,
    title: "Desenvolvedor Back-end Sênior",
    description: "Procuramos um desenvolvedor Back-end para liderar e trabalhar em projetos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, tem ampla experiência em liderar equipes e projetos, além de habilidades em comunicação e colaboração.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "Express.js",
      "SQL",
      "MongoDB",
      "AWS",
      "Docker",
      "REST API",
      "Jest",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Sênior",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 9.000,00 - R$ 14.000,00",
    publication: "2023-04-08"
  },
  {
    id: 9,
    title: "Desenvolvedor Full-stack Sênior",
    description: "Procuramos um desenvolvedor Full-stack para liderar e trabalhar em projetos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, tem ampla experiência em liderar equipes e projetos, além de habilidades em comunicação e colaboração.",
    career_focus: "Full-stack",
    required_skills: [
      "JavaScript",
      "React",
      "Redux",
      "Node.js",
      "Express.js",
      "SQL",
      "MongoDB",
      "AWS",
      "Git",
      "ES6+",
      "Webpack",
      "Jest"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "Belo Horizonte - MG",
    salary_range: "R$ 10.000,00 - R$ 15.000,00",
    publication: "2023-04-08"
  },
  {
    id: 10,
    title: "Desenvolvedor Back-end Sênior",
    description: "Estamos buscando um desenvolvedor Back-end Sênior para liderar projetos de alta complexidade, com foco em escalabilidade e performance. O candidato ideal é capaz de trabalhar em equipe, possui conhecimento avançado em arquitetura de software e experiência comprovada em projetos de grande porte.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "SQL",
      "NoSQL",
      "API design",
      "AWS",
      "Microservices",
      "Docker",
      "Kubernetes",
      "Git"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "São Paulo - SP",
    salary_range: "R$ 12.000,00 - R$ 16.000,00",
    publication: "2023-04-08"
  },
  {
    id: 11,
    title: "Desenvolvedor Full-stack Pleno",
    description: "Procuramos um desenvolvedor Full-stack Pleno para trabalhar em projetos desafiadores, com foco em qualidade e performance. O candidato ideal possui conhecimento avançado em tecnologias front-end e back-end, é capaz de liderar projetos e trabalhar em equipe.",
    career_focus: "Full-stack",
    required_skills: [
      "React",
      "Angular",
      "Node.js",
      "SQL",
      "NoSQL",
      "API design",
      "AWS",
      "Docker",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Pleno",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 7.000,00 - R$ 10.000,00",
    publication: "2023-04-08"
  },
  {
    id: 12,
    title: "Desenvolvedor Front-end Júnior",
    description: "Estamos em busca de um desenvolvedor Front-end Júnior para fazer parte do nosso time e trabalhar em projetos de alta qualidade. O candidato ideal é apaixonado por tecnologia, possui conhecimento em tecnologias front-end e é capaz de trabalhar em equipe.",
    career_focus: "Front-end",
    required_skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Vue.js",
      "Sass",
      "Webpack",
      "Jest",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Júnior",
    type_job: "Presencial",
    location: "Rio de Janeiro - RJ",
    salary_range: "R$ 2.500,00 - R$ 3.500,00",
    publication: "2023-04-08"
  },
  {
    id: 13,
    title: "Desenvolvedor Back-end Sênior",
    description: "Estamos buscando um desenvolvedor Back-end Sênior para liderar nossos projetos e garantir alta qualidade e escalabilidade em nossas aplicações. O candidato ideal possui vasta experiência em arquitetura de software, programação orientada a objetos e desenvolvimento de APIs RESTful.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "Express",
      "MongoDB",
      "Redis",
      "AWS",
      "Docker",
      "TDD",
      "Design Patterns",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "São Paulo - SP",
    salary_range: "R$ 12.000,00 - R$ 15.000,00",
    publication: "2023-04-08"
  },
  {
    id: 14,
    title: "Desenvolvedor Front-end Sênior",
    description: "Procuramos um desenvolvedor Front-end Sênior para liderar a implementação de nossas interfaces web e garantir alta performance e usabilidade em nossas aplicações. O candidato ideal possui ampla experiência em desenvolvimento de interfaces web responsivas e acessíveis, além de conhecimentos em tecnologias emergentes como React e Next.js.",
    career_focus: "Front-end",
    required_skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React",
      "Redux",
      "Webpack",
      "Accessibility",
      "Performance Optimization",
      "Design Systems"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 15.000,00 - R$ 18.000,00",
    publication: "2023-04-08"
  },
  {
    id: 15,
    title: "Desenvolvedor Full-stack Sênior",
    description: "Estamos buscando um desenvolvedor Full-stack Sênior para liderar o desenvolvimento de nossas aplicações web e garantir alta qualidade e usabilidade. O candidato ideal possui experiência tanto em desenvolvimento front-end quanto back-end, além de conhecimentos em arquitetura de software e desenvolvimento de APIs RESTful.",
    career_focus: "Full-stack",
    required_skills: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Redis",
      "AWS",
      "Docker",
      "TDD",
      "CI/CD"
    ],
    type_contract: "CLT",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "Rio de Janeiro - RJ",
    salary_range: "R$ 15.000,00 - R$ 20.000,00",
    publication: "2023-04-08"
  },
  {
    id: 16,
    title: "Desenvolvedor Back-end Pleno",
    description: "Procuramos um desenvolvedor Back-end para integrar a equipe e trabalhar em projetos de alta complexidade. O candidato ideal é apaixonado por tecnologia, curioso e capaz de trabalhar em equipe.",
    career_focus: "Back-end",
    required_skills: [
      "Java",
      "Spring Boot",
      "Kotlin",
      "MySQL",
      "Git",
      "Docker",
      "REST",
      "Microserviços",
      "Jenkins"
    ],
    type_contract: "PJ",
    seniority_level: "Pleno",
    type_job: "Presencial",
    location: "São Paulo - SP",
    salary_range: "R$ 5.000,00 - R$ 7.000,00",
    publication: "2023-04-08"
  },
  {
    id: 17,
    title: "Desenvolvedor Mobile Sênior",
    description: "Procuramos um desenvolvedor mobile para liderar o desenvolvimento de aplicativos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal possui vasta experiência em desenvolvimento nativo para Android e/ou iOS, é apaixonado por tecnologia, curioso e capaz de trabalhar em equipe.",
    career_focus: "Mobile",
    required_skills: [
      "Java",
      "Kotlin",
      "Swift",
      "Objective-C",
      "React Native",
      "Flutter",
      "Git",
      "Agile",
      "UI/UX Design"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "São Paulo - SP",
    salary_range: "R$ 10.000,00 - R$ 12.000,00",
    publication: "2023-04-08"
  },
  {
    id: 18,
    title: "Desenvolvedor Mobile iOS Sênior",
    description: "Buscamos um desenvolvedor Mobile iOS Sênior para liderar o desenvolvimento de aplicativos iOS de alta qualidade. O candidato ideal deve possuir sólido conhecimento em Swift e experiência em projetos de grande escala.",
    career_focus: "Mobile",
    required_skills: [
      "Swift",
      "Objective-C",
      "Cocoa Touch",
      "RESTful API",
      "Git",
      "Agile",
      "Continuous Integration",
      "Automated Testing",
      "Code Review"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "São Paulo - SP",
    salary_range: "R$ 10.000,00 - R$ 12.000,00",
    publication: "2023-04-08"
  },
  {
    id: 19,
    title: "Desenvolvedor Mobile Android Pleno",
    description: "Procuramos um desenvolvedor Mobile Android Pleno para desenvolver aplicativos de alta qualidade em uma equipe ágil e colaborativa. O candidato ideal deve possuir conhecimento em Kotlin e experiência em projetos mobile.",
    career_focus: "Mobile",
    required_skills: [
      "Kotlin",
      "Java",
      "Android Studio",
      "RESTful API",
      "Git",
      "Agile",
      "Continuous Integration",
      "Automated Testing",
      "Code Review"
    ],
    type_contract: "CLT",
    seniority_level: "Pleno",
    type_job: "Híbrido",
    location: "Rio de Janeiro - RJ",
    salary_range: "R$ 6.000,00 - R$ 8.000,00",
    publication: "2023-04-08"
  },
  {
    id: 20,
    title: "Desenvolvedor Mobile Full-stack Sênior",
    description: "Estamos em busca de um desenvolvedor Mobile Full-stack Sênior para liderar a equipe de desenvolvimento de aplicativos. O candidato ideal deve possuir conhecimento em React Native e experiência em projetos full-stack.",
    career_focus: "Mobile",
    required_skills: [
      "React Native",
      "Node.js",
      "RESTful API",
      "Git",
      "Agile",
      "Continuous Integration",
      "Automated Testing",
      "Code Review",
      "MySQL"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 15.000,00 - R$ 18.000,00",
    publication: "2023-04-08"
  },
  {
    id: 21,
    title: "Designer Júnior",
    description: "Procuramos um designer júnior com vontade de aprender e crescer em um ambiente criativo e inovador. O candidato ideal possui conhecimentos em ferramentas de design gráfico e prototipação, além de habilidades em comunicação e trabalho em equipe.",
    career_focus: "Design",
    required_skills: [
      "Photoshop",
      "Illustrator",
      "Figma",
      "InVision",
      "Comunicação",
      "Criatividade",
      "Trabalho em equipe",
      "Atenção aos detalhes",
      "Habilidade para seguir diretrizes de branding"
    ],
    type_contract: "CLT",
    seniority_level: "Júnior",
    type_job: "Presencial",
    location: "São Paulo - SP",
    salary_range: "R$ 1.000,00 - R$ 1.500,00",
    publication: "2023-04-08"
  },
  {
    id: 22,
    title: "Designer UX/UI Pleno",
    description: "Procuramos um designer UX/UI pleno para trabalhar em uma equipe multidisciplinar de design e desenvolvimento de software. O candidato ideal tem forte habilidade em design de interface do usuário e empatia com o usuário final, bem como experiência em design de produto e testes de usabilidade.",
    required_skills: [
      "Design de interface do usuário",
      "Design de produtos",
      "Testes de usabilidade",
      "Ferramentas de design (Sketch, Figma, InVision)",
      "Gerenciamento de projetos"
    ],
    type_contract: "CLT",
    seniority_level: "Pleno",
    type_job: "Híbrido",
    location: "São Paulo",
    salary_range: "R$ 4.000,00 - R$ 6.000,00",
    publication: "2023-04-09"
  }
]