export const data = [ 
  {
    id: 1,
    title: "Desenvolvedor Front-end Júnior",
    description: "Procuramos um desenvolvedor Front-end para trabalhar em projetos de alta qualidade em um ambiente ágil e dinâmico. O candidato ideal é apaixonado por tecnologia, curioso e capaz de trabalhar em equipe.",
    career_focus: "Front-end",
    required_skills: [
      "JavaScript",
      "React",
      "Sass",
      "Jest",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Júnior",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 2.500,00 - R$ 3.500,00",
    publication: "2023-04-08",
  },
  {
    id: 2,
    title: "Desenvolvedor Back-end Júnior",
    description: "Estamos em busca de um desenvolvedor back-end júnior para integrar nosso time e contribuir com o desenvolvimento de soluções inovadoras. O candidato ideal deve ter conhecimento em tecnologias como Node.js, SQL e Git, além de ser proativo, colaborativo e estar disposto a aprender.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "Express",
      "MongoDB",
      "REST API",
      "Git"
    ],
    type_contract: "PJ",
    seniority_level: "Júnior",
    type_job: "Presencial",
    location: "Cabo Frio, RJ",
    salary_range: "R$ 3.500,00 - R$ 6.500,00",
    publication: "2023-04-08"
  },
  {
    id: 3,
    title: "Desenvolvedor Front-end Pleno",
    description: "Estamos em busca de um desenvolvedor front-end pleno para integrar nosso time e contribuir com o desenvolvimento de soluções inovadoras. O candidato ideal deve ter conhecimento em tecnologias como React, TypeScript e Git, além de ser proativo, colaborativo e estar disposto a aprender.",
    career_focus: "Front-end",
    required_skills: [
      "React",
      "Next.js",
      "TypeScript",
      "CSS-in-JS",
      "GraphQL",
      "Vue.js",
      "SASS",
      "Webpack",
      "Git"
    ],
    type_contract: "CLT",
    seniority_level: "Pleno",
    type_job: "Presencial",
    location: "São Paulo, SP",
    salary_range: "R$ 4.000,00 - R$ 8.000,00",
    publication: "2023-04-09"
  },
  {
    id: 4,
    title: "Desenvolvedor Back-end Pleno",
    description: "Estamos em busca de um desenvolvedor back-end pleno para integrar nosso time e contribuir com o desenvolvimento de soluções inovadoras. O candidato ideal deve ter conhecimento em tecnologias como Node.js, TypeScript, Docker e Git, além de ser proativo, colaborativo e estar disposto a aprender.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "TypeScript",
      "Docker",
      "AWS",
      "Kubernetes",
      "PostgreSQL",
      "REST API",
      "Jest",
      "Git"
    ],
    type_contract: "PJ",
    seniority_level: "Pleno",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 6.500,00 - R$ 10.000,00",
    publication: "2023-04-09"
  },
  {
    id: 5,
    title: "Desenvolvedor Front-end Sênior",
    description: "Estamos em busca de um desenvolvedor front-end sênior para liderar a equipe de desenvolvimento front-end e contribuir com o desenvolvimento de soluções inovadoras. O candidato ideal deve ter conhecimento em tecnologias como React, Vue.js, Angular, TypeScript e Git, além de ser proativo, colaborativo e estar disposto a aprender.",
    career_focus: "Front-end",
    required_skills: [
      "React",
      "Vue.js",
      "Angular",
      "TypeScript",
      "Webpack",
      "ES6+",
      "CSS-in-JS",
      "GraphQL",
      "RxJS",
      "Jest",
      "Cypress",
      "Next.js",
      "SASS",
      "Accessibility"
    ],
    type_contract: "CLT",
    seniority_level: "Sênior",
    type_job: "Presencial",
    location: "Rio de Janeiro, RJ",
    salary_range: "R$ 10.000,00 - R$ 16.000,00",
    publication: "2023-04-09"
  },
  {
    id: 6,
    title: "Desenvolvedor Back-end Sênior",
    description: "Estamos em busca de um desenvolvedor back-end sênior para liderar a equipe de desenvolvimento back-end e contribuir com o desenvolvimento de soluções inovadoras. O candidato ideal deve ter conhecimento em tecnologias como Node.js, TypeScript, AWS, Docker e Git, além de ser proativo, colaborativo e estar disposto a aprender.",
    career_focus: "Back-end",
    required_skills: [
      "Node.js",
      "TypeScript",
      "AWS",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "REST API",
      "GraphQL",
      "Git",
      "Jest",
      "Express",
      "Nest.js",
      "Serverless",
      "CI/CD"
    ],
    type_contract: "PJ",
    seniority_level: "Sênior",
    type_job: "Remoto",
    location: "Qualquer lugar do Brasil",
    salary_range: "R$ 15.000,00 - R$ 20.000,00",
    publication: "2023-04-09"
  }    
]